title       = "vndirect"
baseURL     = "https://vndirect-cli.tamnd.com/"
description = "A command line for vndirect."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/vndirect-cli"
